# file: cassandra/tasks/package_configure.yml

- name: Cassandra | Update the cassandra configuration
  template:
    src: "{{item}}.j2"
    dest: "/etc/cassandra/{{item}}"
    owner: "{{cassandra_user}}"
    group: "{{cassandra_group}}"
    mode: 0644
  with_items:
    - "cassandra-env.sh"
    - "cassandra.yaml"
    - "system_auth.cql"
    - "auth_users.cql"

- name: stop cassandra
  service:
    name: cassandra
    state: stopped

- name: wait for stopping cassandra
  pause: seconds=40 prompt="Make sure cassandra was stopped"

- name: change authenticator
  lineinfile:
    dest: /etc/cassandra/cassandra.yaml
    state: present
    regexp: '^authenticator'
    line: 'authenticator: PasswordAuthenticator'

- name: clean cassandra directories
  shell: rm -rf {{ cassandra_data_file_directories }} {{ cassandra_commitlog_directory }} {{ cassandra_saved_caches_directory }}

- name: Restart cassandra
  service:
    name: cassandra
    state: restarted

- name: waiting restart cassandra to join cluster
  pause: prompt="waiting restart cassandra before change system aut"

- name: change system auth replication
  shell: /usr/bin/cqlsh {{ cassandra_listen_address }} {{ cassandra_native_transport_port }}  -u cassandra -p cassandra -f /etc/cassandra/system_auth.cql

- name: repair node
  shell: /usr/bin/nodetool repair

- name: rebuild node
  shell: /usr/bin/nodetool rebuild

- name: restart after changed authenticator
  service:
    name: cassandra
    state: restarted

- name: waiting after changed authenticator
  pause: prompt="waiting after changed authenticator"

- name: create new superuser and disable cassandra
  shell: /usr/bin/cqlsh {{ cassandra_listen_address }} {{ cassandra_native_transport_port }} -u cassandra -p cassandra -f /etc/cassandra/auth_users.cql

